name: hadolint

on:
  workflow_call:

concurrency:
  group: hadolint-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
