name: shellcheck

on:
  workflow_call:

concurrency:
  group: shellcheck-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: Lint shell scripts
        uses: ludeeus/action-shellcheck@master
        with:
          format: diff
