# This workflow will lint shell scripts, yml, and dockerfiles and test calver
name: Test

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: test-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  test:
    name: Test calver action outputs
    runs-on: ubuntu-latest
    needs: [ lint ]
    steps:
      - uses: actions/checkout@v4
      - name: actions-calver
        id: calver
        uses: ./
        with:
          release: false
          patch_separator: "-"
          date_format: "%Y.%m.%d"
          draft: true
          pre: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: calver output
        env:
          NAME: "${{ steps.calver.outputs.name }}"
          RELEASE: "${{ steps.calver.outputs.release }}"
          DRAFT: "${{ steps.calver.outputs.draft }}"
          PRE: "${{ steps.calver.outputs.pre }}"
          MESSAGE: "${{ steps.calver.outputs.message }}"
        run: |
          echo "$NAME"
          echo "$RELEASE"
          echo "$DRAFT"
          echo "$PRE"
          echo "$MESSAGE"
